import com.google.common.annotations.VisibleForTesting;
import org.junit.*;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import java.util.concurrent.TimeUnit;
import static org.junit.Assert.*;

public class autoGenerateStudent    {

    private static WebDriver driver;
    int random = ((int)(Math.random()*9999)+1);

    @BeforeClass
    public static void setUpChrome() {
        // Create a new WebDriver instance (Use Chrome)
        // download ChromeDriver and put the path here...
        System.setProperty("webdriver.chrome.driver", "ChromeDriver\\chromedriver.exe");
        driver = new ChromeDriver();
    }

    @Test
    public void registerTest() throws Exception {

        //HEY! IF YOU'RE READING THIS YOU PROBABLY WANT TO READ THIS
        //Make sure you have Apache and MySQL running before performing this test.
        //The password for autogenerated users is "Password1", case sensitive
        driver.get("http://localhost/project-review/temp_reg.php");
        random = ((int)(Math.random()*9999)+1);

        WebElement element = driver.findElement(By.name("fname"));
        element.sendKeys("user" + random);
        element = driver.findElement(By.name("lname"));
        element.sendKeys("autogenerated");
        element = driver.findElement(By.name("phone"));
        element.sendKeys("678" + (int)(Math.random()*998 + 1) + "9999");
        element = driver.findElement(By.name("email"));
        element.sendKeys("user" + random + "@url.com");
        element = driver.findElement(By.name("password"));
        element.sendKeys("Password1");
        element = driver.findElement(By.name("confirm"));
        element.sendKeys(("Password1"));

        driver.findElement(By.xpath("//input[@value='Register' and @type='button']")).click();

        element = driver.findElement(By.name("email"));
        element.sendKeys("user" + random + "@url.com");
        driver.findElement(By.name("password")).sendKeys("Password1");
        driver.findElement(By.xpath("//button[@value='Login' and @type='submit']")).click();
    }


}